### PR TITLE
Move currently used frameworks to correct place in paper

### PR DESCRIPTION
**Pull request by jverbraeken**
It was under "methods" and should be under "currently used implementations"

### CODE REVIEW

**Comment by mwolting** [comment]
My PR contains a plugin to number paragraphs automatically, so you can get rid of the manual numbers

**Comment by mwolting** [comment]
*contained

**Review by Kloppie5 — APPROVED** [review]
lgtm

**Review by mwolting — CHANGES_REQUESTED** [review]
My PR contained a plugin to number paragraphs automatically, so you can get rid of the manual numbers

**Comment by Kloppie5** [comment]
The existence of a solution in a different PR is no reason to request changes here. This PR also contains different, important changes.

**Comment by mwolting** [comment]
It very much is. This PR should not be merged before the manual numbers are removed from the paragraph, otherwise there will be duplicate numbers.

**Review by mwolting — APPROVED** [review]

**Pull request merged**
